name: "Install PHP Dependencies with Composer using optionally dependencies.json"
description: "Installs PHP dependencies using Composer. If a dependencies.json file is present, it updates composer.json accordingly before installation."
author: 'Ibexa AS'

runs:
    using: "composite"
    steps:
        -   name: Set GitHub Path
            run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
            shell: bash
            env:
                GITHUB_ACTION_PATH: ${{ github.action_path }}

        -   name: 'Process dependencies.json and update composer.json'
            shell: bash
            run: |
                if [[ -f dependencies.json ]]
                then
                  composer-replace-dependencies.bash dependencies.json
                fi

        -   uses: ramsey/composer-install@v3
            with:
                dependency-versions: highest
